#Avaiable Variables:
#{onlinePlayersCountServer} -> The number of players of the server you are connected on.
#{onlinePlayersCountProxy} -> The number of players of the proxyServer you are connected on.
#{onlinePlayersCountGlobal} -> The number of players of the whole network.
#{serverGroup} -> The name of the serverGroup you are connected on.
#{proxyGroup} -> The name of the proxyGroup you are connected on.
#{proxyName} -> The name of the proxyServer you are connected on.
#{serverName} -> The name of the server you are connected on.
#{playerName} -> Your playerName.
#{playerUUID} -> Your playerUUID.
#{serverMOTD] -> The motd of the server you are connected on.
#{proxyMOTD} -> The motd of the proxyServer you are connected on.
#{proxyBASE} -> The baseName of the proxyServer you are connected on.
#{serverBASE} -> The baseName of the server you are connected on.
#{serverState} -> The serverState of the server you are connected on.
#{serverExtra} -> The serverExtra of the server you are connected on.
#{maxPlayerCountServer} -> The maxPlayerCount of the server you are connected on.
#{maxPlayerCountProxy} -> The maxPlayerCount of the proxy you are connected on.
#{maxPlayerCountGlobal} -> The maxPlayerCount of the whole network.

header: "\n&8● &YourServer.com &8➜ &4perhaps your slogan?  &8●\n&8● &7Players online &8➜ &4{onlinePlayersCountGlobal}&8/&4{maxPlayerCountGlobal} &8●\n"
footer: "\n&7Demo &8➜ &4Demo Tablist &8&l| &7Demo³ &8➜ &4Tablist\n&7Demo &8➜ &4Tablist\n"
